# Generated by Django 3.2.5 on 2023-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('side', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=10)),
                ('time_in_force', models.CharField(max_length=10)),
                ('original_quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('average_price', models.FloatField()),
                ('order_status', models.CharField(max_length=10)),
                ('order_last_filled_quantity', models.FloatField()),
                ('order_filled_accumulated_quantity', models.FloatField()),
                ('order_trade_time', models.DateTimeField()),
            ],
        ),
    ]
